export const Rule = {
  START_LIVE_COUNT: 3,
  CORRECT_ANSWER_AWARD: 100,
  PER_LIVE_AWARD: 50,
  FAST_ANSWER_AWARD: 50,
  SOLOW_ANSWER_PENALTY: 50,
  LOSE_POINTS: -1,
  QUESTIONS_COUNT: 10,
  FAST_ANSWER_TIME: 10,
  SLOW_ANSWER_TIME: 20,
};
